### ISSUE TITLE
Getting an error after all dependencies were installed

### ISSUE THREAD

**Issue by anthonymonori** [anthonymonori/python-minigames#3]
```
Traceback (most recent call last):
  File "GuessTheNr-week2.py", line 9, in <module>
    import simpleplot
  File "build/bdist.macosx-10.11-x86_64/egg/simpleplot/__init__.py", line 5, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/simpleplot/plot.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

Running on Mac OSX 10.11.4

**Comment by anthonymonori** [comment]
Issue caused by bash profile.

If you have the same issue, please run the following two lines in your terminal:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

[Source](http://stackoverflow.com/a/19961403/2759296)
